### ISSUE TITLE
Unable to load configuration.

### ISSUE THREAD

**Issue by skyaee** [AndrewEllis93/Ellis-SuperSlicer-Profiles#16]
Unable to load configuration.
![image](https://user-images.githubusercontent.com/40803751/201329215-87e83f3b-836f-447d-9a09-90443d292ffa.png)
![image](https://user-images.githubusercontent.com/40803751/201329251-4cc85d5b-5722-452d-abcd-cd176d307140.png)
<img width="1014" alt="A70DAE61C39D3609EC2AE1F5F7122CA1" src="https://user-images.githubusercontent.com/40803751/201329283-13dfa34c-7d6c-4bbb-a40f-312774ace374.png">

**Comment by AndrewEllis93** [comment]
Import as config, not as config **bundle**.

Also please try the recommended version of SuperSlicer (2.4.58.5).

And did you download using the instructions?

**Comment by skyaee** [comment]
> 导入为配置，而不是配置**包**。
> 
> 也请尝试推荐版本的 SuperSlicer (2.4.58.5)。
> 
> 你是按照说明下载的吗？
<img width="1273" alt="截屏2022-11-12 00 03 12" src="https://user-images.githubusercontent.com/40803751/201381305-073044f2-6f34-480d-96d5-dfcbc3879795.png">
Yes, follow the tutorial process exactly, the same is true for version 2.4.58.

**Comment by skyaee** [comment]
https://user-images.githubusercontent.com/40803751/201381953-2c6001a8-6822-489b-9cc5-ff17ff83df6c.mov

**Comment by AndrewEllis93** [comment]
I am unable to replicate this issue. 
Please upload the exact ini file you are using here, just want to make sure it looks good.
Could also be something different with the Mac version, I use Windows

**Comment by skyaee** [comment]
[config.ini.zip](https://github.com/AndrewEllis93/Ellis-SuperSlicer-Profiles/files/9992285/config.ini.zip)
My current configuration file is the default configuration file of the software.

**Comment by AndrewEllis93** [comment]
Sorry, I mean the ini file you are trying to import, in your video

**Comment by skyaee** [comment]
[归档.zip](https://github.com/AndrewEllis93/Ellis-SuperSlicer-Profiles/files/9992312/default.zip)
Sorry, I misunderstood, this is the file.

**Comment by AndrewEllis93** [comment]
You have downloaded the file as HTML instead of raw
Are you using the "raw" button as shown?
![image](https://user-images.githubusercontent.com/34943186/201396574-d2f0ec6f-dc6c-4a70-85f5-1f63c6b23b29.png)

**Comment by skyaee** [comment]
Thank you, it is the file download problem, I have no problem with the new download. thanks.
