### ISSUE TITLE
External Perimeter Adhesion Issue

### ISSUE THREAD

**Issue by BuddyBing** [AndrewEllis93/Ellis-SuperSlicer-Profiles#18]
On the latest version of your profile, I started to have some issues where the external perimeter wasn't adhering to the next internal perimeter.  I ended up having to change the external perimeter from your 100% to 105% which resolves the issue but am just curious if I am missing something?  I believe in your older profiles this was set to 0 (ie. use default width)?

**Comment by AndrewEllis93** [comment]
Currently the only reason it's set to 100% is for Voron parts, to keep somewhat in line with official printing guidelines - it is a PIF profile, after all. I'm actually not a fan of 100% widths at all.

I'm actually printing some PIF sets with 112.5%-115% widths for testing and may update this.

(along with an even faster profile that I may release as an "expert" profile, and SS 2.5 compatibility 🙂)
